seed: 1
max_epoch: 40
max_session_epoch: 40
block_size: 40
block_decay: .5
optimizer: pSGLD
model: inception # inception | resnet | densenet
drop_rate: .0
pretrained: True
pSGLD:
  lr: 1.e-4
  train_size: 2746 # 1373
  alpha: .95
  eps: 5.e-5
  num_burn_in_steps: 300
  centered: False
  addnoise: True
  _decay_by_loss: False
  _decay_rate: .1
dataset:
  batch_size: 64
  mean: [0.4064, 0.2913, 0.1175]
  std: [0.3019, 0.2125, 0.1318]
  train_dataset: /kaggle/tmp/ddr-clahe/train
  valid_dataset: /kaggle/tmp/ddr-clahe/test
  heldout_dataset: /kaggle/tmp/ddr-clahe/valid
class_weight:
  samples_per_class: [3132,2671,456]
  method: none # ins | isns | ens | none
  beta: 0.999 # only valid for ens
  per_minibatch: False