seed: 1
max_epoch: 100
max_session_epoch: 30
block_size: 20
block_decay: .5
# model: resnet.ResNet18
optimizer: pSGLD
pSGLD:
  lr: 1.e-4
  train_size: 10000
  alpha: .95
  eps: 5.e-5
  num_burn_in_steps: 300
  centered: False
  addnoise: True
dataset:
  positive_weight: 3.
  batch_size: 32
  train_dataset: /kaggle/tmp/eyepacs/eyepacs_balanced/train
  valid_dataset: /kaggle/tmp/eyepacs/eyepacs_balanced/test
  heldout_dataset: /kaggle/tmp/eyepacs/eyepacs_balanced/heldout