seed: 1
max_epoch: 300
max_session_epoch: 100
block_size: 20
block_decay: .5
optimizer: EKSGLD
EKSGLD:
  lr: 1.e-2
  train_size: 10000
  num_burn_in_steps: 600
  add_noise: True
  eps: 1.e-2   # Tikhonov regularization
  sua: False  # Applies SUA approximation.
  ra: True
  update_freq: 50
  alpha: .5   # Running average parameter (if == 1, no r. ave.).
  update_style: ksgld
  _accept_model: True
dataset:
  positive_weight: 1.
  batch_size: 32
  train_dataset: /kaggle/tmp/eyepacs/eyepacs_balanced/train
  valid_dataset: /kaggle/tmp/eyepacs/eyepacs_balanced/test
  heldout_dataset: /kaggle/tmp/eyepacs/eyepacs_balanced/heldout