seed: 1
max_epoch: 45
max_session_epoch: 5
block_size: 20
block_decay: .5
optimizer: pSGLD
model: inception # inception | resnet | densenet
pSGLD:
  lr: 1.e-4
  train_size: 42717
  alpha: .95
  eps: 5.e-5
  num_burn_in_steps: 300
  centered: False
  addnoise: True
dataset:
  batch_size: 32
  train_dataset: /kaggle/tmp/eyepacs/eyepacs-multiclass/train
  valid_dataset: /kaggle/tmp/eyepacs/eyepacs-multiclass/test
  heldout_dataset: /kaggle/tmp/eyepacs/eyepacs-multiclass/heldout
class_weight:
  samples_per_class: [31699,10187,831]
  method: ens # ins | isns | ens
  beta: 0.999 # only valid for ens