seed: 1
max_epoch: 30
max_session_epoch: 30
block_size: 40
block_decay: .5
optimizer: RMSprop
model: inception # inception | resnet | densenet
drop_rate: .0
pretrained: True
RMSprop:
  lr: 1.e-4
  alpha: .95
  eps: 5.e-5
  centered: False
  _decay_by_loss: False
  _decay_rate: .1
dataset:
  augmentation: FILOS_2019
  color_jitter: True
  batch_size: 64
  mean: [0.4064, 0.2913, 0.1175]
  std: [0.3019, 0.2125, 0.1318]
  train_dataset: /kaggle/tmp/ddr-clahe/train
  valid_dataset: /kaggle/tmp/ddr-clahe/test
  heldout_dataset: /kaggle/tmp/ddr-clahe/valid
  oversampling: False
  count_samples: 9396 # 3132x3 (number samples from the largest class i.e class 0 in training dataset, times number of classes)
class_weight:
  samples_per_class: [3132,2671,456]
  method: none # ins | isns | ens | none
  beta: 0.99 # only valid for ens
  per_minibatch: False