seed: 1
max_epoch: 40
max_session_epoch: 30
block_size: 40
block_decay: .5
optimizer: RMSProp
model: inception # inception | resnet | densenet
RMSProp:
  lr: 1.e-3
  weight_decay: 4.e-5
dataset:
  batch_size: 64
  mean: [0.5,0.5,0.5]
  std: [0.5,0.5,0.5]
  train_dataset: /kaggle/tmp/ddr-clahe/train
  valid_dataset: /kaggle/tmp/ddr-clahe/test
  heldout_dataset: /kaggle/tmp/ddr-clahe/valid
class_weight:
  samples_per_class: [3132,2671,456]
  method: ens # ins | isns | ens | none
  beta: 0.999 # only valid for ens
  per_minibatch: False