seed: 1
max_epoch: 10
max_session_epoch: 5
block_size: 20
block_decay: .5
optimizer: pSGLD
model: inception # inception | resnet | densenet
pSGLD:
  lr: 1.e-4
  train_size: 6264
  alpha: .95
  eps: 5.e-5
  num_burn_in_steps: 300
  centered: False
  addnoise: True
dataset:
  batch_size: 64
  train_dataset: /kaggle/tmp/ddr-clahe/train
  valid_dataset: /kaggle/tmp/ddr-clahe/test
  heldout_dataset: /kaggle/tmp/ddr-clahe/valid
class_weight:
  samples_per_class: [3132,2671,456]
  method: none # ins | isns | ens | none
  beta: 0.999 # only valid for ens