seed: 1
trials: 5
epoch: 5
block_size: 20
block_decay: .5
optimizer: pSGLD
RMSprop:
  fixed:
    weight_decay: 4.e-5
  tune:
    lr:
      categorical:
        choices: [1.e-4, 1.e-3, 1.e-2]
SGLD:
  fixed:
    train_size: 14000
    lr_decay: 2.e-2
    weight_decay: 0.
    num_burn_in_steps: 300
  tune:
    lr:
      categorical:
        choices: [5.e-3, 5.e-2, .15, .5]
pSGLD:
  fixed:
    train_size: 14000
    alpha: .95
    eps: 5.e-5
    num_burn_in_steps: 300
    centered: False
    addnoise: True
  tune:
    lr:
      categorical:
        choices: [1.e-5, 1.e-4, 1.e-3, 1.e-2, .1]
ASGLD:
  fixed:
    momentum: .9
    weight_decay: 5.e-4
    eps: 1.e-6
  tune:
    lr:
      categorical:
        choices: [1.e-2, 1.e-1, 5.e-1]
    noise:
      categorical:
        choices: [1.e-2, 1.e-1]
KSGLD:
  fixed:
      train_size: 14000
      num_burn_in_steps: 600
      add_noise: True
      eps: 1.e-3   # Tikhonov regularization
      sua: True  # Applies SUA approximation.
      pi: False   # pi conrrection for Tikhonov regularization
      update_freq: 50
      alpha: 1.   # Running average parameter (if == 1, no r. ave.).
      constraint_norm: True  # Scale the gradients by the squared fisher norm.
      _accept_model: True
  tune:
    lr:
      categorical:
        choices: [1.e-2, 3.2e-2, 1.e-1]
    eps:
      categorical:
        choices: [1.e-3, 1.e-2]
EKSGLD:
  fixed:
      train_size: 14000
      num_burn_in_steps: 600
      add_noise: True
      sua: False  # Applies SUA approximation.
      ra: True
      update_freq: 50
      alpha: .5   # Running average parameter (if == 1, no r. ave.).
      update_style: ksgld
      _accept_model: True
  tune:
    lr:
      categorical:
        choices: [1.e-3, 5.e-3, 1.e-2]
    eps:
      categorical:
        choices: [1.e-3, 1.e-2]
dataset:
  batch_size: 32
  train_dataset: /kaggle/tmp/eyepacs/eyepacs-multiclass/train
  valid_dataset: /kaggle/tmp/eyepacs/eyepacs-multiclass/test
  heldout_dataset: /kaggle/tmp/eyepacs/eyepacs-multiclass/heldout
class_weight:
  samples_per_class: [10500,3390,277]
  method: ens # ins | isns | ens
  beta: 0.999 # only valid for ens