seed: 1
trials: 5
epoch: 10
block_size: 20
block_decay: .5
optimizer: RMSprop
RMSprop:
  fixed:
    weight_decay: 4.e-5
  tune:
    lr:
      categorical:
        choices: [1.e-3, 1.e-2]
SGLD:
  fixed:
    train_size: 10000
    lr_decay: 2.e-2
    weight_decay: 0.
    num_burn_in_steps: 300
  tune:
    lr:
      categorical:
        choices: [5.e-5, 5.e-4, 5.e-3, 5.e-2, .5]
dataset:
  batch_size: 128
  train_dataset: /kaggle/tmp/eyepacs/eyepacs_balanced/train
  valid_dataset: /kaggle/tmp/eyepacs/eyepacs_balanced/test
  heldout_dataset: /kaggle/tmp/eyepacs/eyepacs_balanced/heldout