seed: 1
trials: 8
epoch: 10
block_size: 20
block_decay: .5
optimizer: pSGLD
pSGLD:
  fixed:
    train_size: 2507
    alpha: .95
    eps: 5.e-5
    num_burn_in_steps: 300
    centered: False
    addnoise: True
  tune:
    lr:
      categorical:
        choices: [1.e-6, 1.e-5, 1.e-4, 1.e-3, 1.e-2, .1]
dataset:
  batch_size: 64
  train_dataset: /kaggle/tmp/ddr-clahe/train
  valid_dataset: /kaggle/tmp/ddr-clahe/test
  heldout_dataset: /kaggle/tmp/ddr-clahe/valid
class_weight:
  samples_per_class: [3132,2671,456]
  method: ens # ins | isns | ens
  beta: 0.999 # only valid for ens